###################################################################

# Created by write_sdc

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current uA
set_load -pin_load 0.05 [get_ports {ms_hour[7]}]
set_load -pin_load 0.05 [get_ports {ms_hour[6]}]
set_load -pin_load 0.05 [get_ports {ms_hour[5]}]
set_load -pin_load 0.05 [get_ports {ms_hour[4]}]
set_load -pin_load 0.05 [get_ports {ms_hour[3]}]
set_load -pin_load 0.05 [get_ports {ms_hour[2]}]
set_load -pin_load 0.05 [get_ports {ms_hour[1]}]
set_load -pin_load 0.05 [get_ports {ms_hour[0]}]
set_load -pin_load 0.05 [get_ports {ls_hour[7]}]
set_load -pin_load 0.05 [get_ports {ls_hour[6]}]
set_load -pin_load 0.05 [get_ports {ls_hour[5]}]
set_load -pin_load 0.05 [get_ports {ls_hour[4]}]
set_load -pin_load 0.05 [get_ports {ls_hour[3]}]
set_load -pin_load 0.05 [get_ports {ls_hour[2]}]
set_load -pin_load 0.05 [get_ports {ls_hour[1]}]
set_load -pin_load 0.05 [get_ports {ls_hour[0]}]
set_load -pin_load 0.05 [get_ports {ms_minute[7]}]
set_load -pin_load 0.05 [get_ports {ms_minute[6]}]
set_load -pin_load 0.05 [get_ports {ms_minute[5]}]
set_load -pin_load 0.05 [get_ports {ms_minute[4]}]
set_load -pin_load 0.05 [get_ports {ms_minute[3]}]
set_load -pin_load 0.05 [get_ports {ms_minute[2]}]
set_load -pin_load 0.05 [get_ports {ms_minute[1]}]
set_load -pin_load 0.05 [get_ports {ms_minute[0]}]
set_load -pin_load 0.05 [get_ports {ls_minute[7]}]
set_load -pin_load 0.05 [get_ports {ls_minute[6]}]
set_load -pin_load 0.05 [get_ports {ls_minute[5]}]
set_load -pin_load 0.05 [get_ports {ls_minute[4]}]
set_load -pin_load 0.05 [get_ports {ls_minute[3]}]
set_load -pin_load 0.05 [get_ports {ls_minute[2]}]
set_load -pin_load 0.05 [get_ports {ls_minute[1]}]
set_load -pin_load 0.05 [get_ports {ls_minute[0]}]
set_load -pin_load 0.05 [get_ports alarm_sound]
create_clock [get_ports clock]  -period 5  -waveform {0 2.5}
set_clock_uncertainty -setup 0.2  [get_clocks clock]
set_clock_uncertainty -hold 0.02  [get_clocks clock]
set_input_delay -clock clock  -max 1.5  [get_ports {key[3]}]
set_input_delay -clock clock  -min 0  [get_ports {key[3]}]
set_input_delay -clock clock  -max 1.5  [get_ports {key[2]}]
set_input_delay -clock clock  -min 0  [get_ports {key[2]}]
set_input_delay -clock clock  -max 1.5  [get_ports {key[1]}]
set_input_delay -clock clock  -min 0  [get_ports {key[1]}]
set_input_delay -clock clock  -max 1.5  [get_ports {key[0]}]
set_input_delay -clock clock  -min 0  [get_ports {key[0]}]
set_input_delay -clock clock  -max 1.5  [get_ports time_button]
set_input_delay -clock clock  -min 0  [get_ports time_button]
set_input_delay -clock clock  -max 1.5  [get_ports alarm_button]
set_input_delay -clock clock  -min 0  [get_ports alarm_button]
set_input_delay -clock clock  -max 1.5  [get_ports fastwatch]
set_input_delay -clock clock  -min 0  [get_ports fastwatch]
set_output_delay -clock clock  -max 1.5  [get_ports {ms_hour[7]}]
set_output_delay -clock clock  -min 0  [get_ports {ms_hour[7]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ms_hour[6]}]
set_output_delay -clock clock  -min 0  [get_ports {ms_hour[6]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ms_hour[5]}]
set_output_delay -clock clock  -min 0  [get_ports {ms_hour[5]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ms_hour[4]}]
set_output_delay -clock clock  -min 0  [get_ports {ms_hour[4]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ms_hour[3]}]
set_output_delay -clock clock  -min 0  [get_ports {ms_hour[3]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ms_hour[2]}]
set_output_delay -clock clock  -min 0  [get_ports {ms_hour[2]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ms_hour[1]}]
set_output_delay -clock clock  -min 0  [get_ports {ms_hour[1]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ms_hour[0]}]
set_output_delay -clock clock  -min 0  [get_ports {ms_hour[0]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ls_hour[7]}]
set_output_delay -clock clock  -min 0  [get_ports {ls_hour[7]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ls_hour[6]}]
set_output_delay -clock clock  -min 0  [get_ports {ls_hour[6]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ls_hour[5]}]
set_output_delay -clock clock  -min 0  [get_ports {ls_hour[5]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ls_hour[4]}]
set_output_delay -clock clock  -min 0  [get_ports {ls_hour[4]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ls_hour[3]}]
set_output_delay -clock clock  -min 0  [get_ports {ls_hour[3]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ls_hour[2]}]
set_output_delay -clock clock  -min 0  [get_ports {ls_hour[2]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ls_hour[1]}]
set_output_delay -clock clock  -min 0  [get_ports {ls_hour[1]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ls_hour[0]}]
set_output_delay -clock clock  -min 0  [get_ports {ls_hour[0]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ms_minute[7]}]
set_output_delay -clock clock  -min 0  [get_ports {ms_minute[7]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ms_minute[6]}]
set_output_delay -clock clock  -min 0  [get_ports {ms_minute[6]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ms_minute[5]}]
set_output_delay -clock clock  -min 0  [get_ports {ms_minute[5]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ms_minute[4]}]
set_output_delay -clock clock  -min 0  [get_ports {ms_minute[4]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ms_minute[3]}]
set_output_delay -clock clock  -min 0  [get_ports {ms_minute[3]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ms_minute[2]}]
set_output_delay -clock clock  -min 0  [get_ports {ms_minute[2]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ms_minute[1]}]
set_output_delay -clock clock  -min 0  [get_ports {ms_minute[1]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ms_minute[0]}]
set_output_delay -clock clock  -min 0  [get_ports {ms_minute[0]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ls_minute[7]}]
set_output_delay -clock clock  -min 0  [get_ports {ls_minute[7]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ls_minute[6]}]
set_output_delay -clock clock  -min 0  [get_ports {ls_minute[6]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ls_minute[5]}]
set_output_delay -clock clock  -min 0  [get_ports {ls_minute[5]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ls_minute[4]}]
set_output_delay -clock clock  -min 0  [get_ports {ls_minute[4]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ls_minute[3]}]
set_output_delay -clock clock  -min 0  [get_ports {ls_minute[3]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ls_minute[2]}]
set_output_delay -clock clock  -min 0  [get_ports {ls_minute[2]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ls_minute[1]}]
set_output_delay -clock clock  -min 0  [get_ports {ls_minute[1]}]
set_output_delay -clock clock  -max 1.5  [get_ports {ls_minute[0]}]
set_output_delay -clock clock  -min 0  [get_ports {ls_minute[0]}]
set_output_delay -clock clock  -max 1.5  [get_ports alarm_sound]
set_output_delay -clock clock  -min 0  [get_ports alarm_sound]
set_input_transition -max 0.2  [get_ports {key[3]}]
set_input_transition -min 0.2  [get_ports {key[3]}]
set_input_transition -max 0.2  [get_ports {key[2]}]
set_input_transition -min 0.2  [get_ports {key[2]}]
set_input_transition -max 0.2  [get_ports {key[1]}]
set_input_transition -min 0.2  [get_ports {key[1]}]
set_input_transition -max 0.2  [get_ports {key[0]}]
set_input_transition -min 0.2  [get_ports {key[0]}]
set_input_transition -max 0.2  [get_ports time_button]
set_input_transition -min 0.2  [get_ports time_button]
set_input_transition -max 0.2  [get_ports alarm_button]
set_input_transition -min 0.2  [get_ports alarm_button]
set_input_transition -max 0.2  [get_ports fastwatch]
set_input_transition -min 0.2  [get_ports fastwatch]
set_false_path   -from [get_ports reset]

